internal/fakecgo: correct the explanation of using closure calls
ebitengine/purego pull request #85
Opened 2022-12-23 16:04 UTC by cuonglm

using the closure calls are partly wrong, and also not clear how this trick works.

This commits rework the explanation, and adding more detail explanation.

Updates #71

2023-01-05 05:05 UTC, hajimehoshi commented
ping @TotallyGamerJet

2023-01-05 05:06 UTC, TotallyGamerJet commented
Waiting on @cuonglm to make the requested changes

2023-01-05 05:07 UTC, cuonglm commented
> Waiting on @cuonglm to make the requested changes

What changes are you talking about?

2023-01-05 14:59 UTC, TotallyGamerJet requested changes
Oh, I guess I never submitted my Review :/

2023-01-05 15:10 UTC, cuonglm commented
> Oh, I guess I never submitted my Review :/

Done.

2023-01-07 01:09 UTC, TotallyGamerJet approved these changes
LGTM!

2023-01-07 01:10 UTC, merged